name: Golong web example
on:
  push:
    branches:
    - 'v1.0'
    tags:
    - 'latest'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          force_push_tag: true
          message: "Lastest release"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          tag: "latest"
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN}}
      - name: Get Repository URL
        id: repo_url
        run: echo "::set-output name=url::https://github.com/${{ github.repository }}"
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload:  |
            {
              "text": "Workshop 2 - CICD  Chen Bochao.",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "DipSA41C CI/CD Assignment Submission"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type":"mrkdwn",
                    "text":"*Name :*\n Chen Bochao"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\n A0276817N"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Email:*\n e1133132@u.nus.edu"
                  }
                },
                {
                  "type": "section",
                  "block_id": "section788",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository :*\n ${{steps.repo_url.outputs.url}}"
                    }
                  ]
                },

                {
                  "type": "section",
                  "block_id": "section789",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Deployment :*\n ${{ secrets.Deployment}}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
